### ISSUE TITLE
Syntax highlight: "let" not contextual

### ISSUE THREAD

**Issue by lemano** [INGCRENGIFO/VsCodeInformix4GL#1]
Hi,

I've detected an error on syntax highlight. You can check it below:

![image](https://user-images.githubusercontent.com/4421832/34988116-76c60240-fab5-11e7-8264-007936464a87.png)

As you can see, **let** from pal**let**, is highlighted, which it shouldn't. Didn't check if it happens with other expressions.

Regards.

P.S.: I'm available to help you with this extension, however need your orientation.

**Comment by lemano** [comment]
Another one:

![image](https://user-images.githubusercontent.com/4421832/35099628-9b111472-fc50-11e7-841e-b53d4166f379.png)

Best Regards

**Comment by INGCRENGIFO** [comment]
Hello, your help is valuable.

I will review and solve it in an update.
