### ISSUE TITLE
Syntax highlight: word "format"

### ISSUE THREAD

**Issue by lemano** [INGCRENGIFO/VsCodeInformix4GL#2]
Hi.

I've found the following situation:

![image](https://user-images.githubusercontent.com/4421832/36269174-639570de-1270-11e8-8441-b1e1b2efcad0.png)

Regards,
Fernando Almeida

**Comment by INGCRENGIFO** [comment]
Hello, I have not managed to reproduce it, here everything looks good.

![imagen](https://user-images.githubusercontent.com/12200313/37040554-24fbc302-2128-11e8-8979-99dbb351b466.png)

share me your code if I see any sequence that causes it.
