### ISSUE TITLE
"then" highlighting problems

### ISSUE THREAD

**Issue by lemano** [INGCRENGIFO/VsCodeInformix4GL#3]
Hi.

I've discovered some more syntax highlighting issues.

As you can see the image below "**then**" keyword remains white when it has spaces after it. If you delete them, "**then**" is correctly highlighted.

![image](https://user-images.githubusercontent.com/4421832/36537283-976d24a4-17c7-11e8-80ef-82d9821b9dc3.png)

In the two pictures below, the difference is the presence of 
parentheses. If you remove them, "**then**" is correctly highlighted.

![image](https://user-images.githubusercontent.com/4421832/36537314-ae58b46c-17c7-11e8-9cf2-dc2c8b53c2ac.png)

![image](https://user-images.githubusercontent.com/4421832/36537359-cbd4d3cc-17c7-11e8-9e43-3e3997291117.png)

Regards,
Fernando

**Comment by INGCRENGIFO** [comment]
Hello, I have not managed to reproduce it, here everything looks good.
![imagen](https://user-images.githubusercontent.com/12200313/37040800-aa83ef0e-2128-11e8-8b42-cb15e5e0fdf5.png)
share me your code if I see any sequence that causes it.

**Comment by lemano** [comment]
Hi... I can't send you the code, but it' doesn't either matter. See please the example below:

![image](https://user-images.githubusercontent.com/4421832/37343758-7162ffe2-26c0-11e8-9779-1b80b4f5195a.png)

There you can see both a correct and incorrect highlighting.

I can send you the details of my vscode:

**Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64**

The list of installed extension:

**2gua.rainbow-brackets
_CristianRengifo.informix4gl_
DotJoshJohnson.xml
DougFinke.vscode-pandoc
HookyQR.beautify
alefragnani.project-manager
dbaeumer.jshint
dbaeumer.vscode-eslint
eg2.tslint
eg2.vscode-npm-script
jinsihou.diff-tool
joaompinto.asciidoctor-vscode
johnpapa.Angular2
kevinkyang.auto-comment-blocks
mkaufman.HTMLHint
msjsdiag.debugger-for-chrome
odubuc.mysql-inline-decorator
robertohuertasm.vscode-icons
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-portuguese
tomoki1207.vscode-input-sequence**

Best regards,
Fernando
